using System.Text.Json;
using System.Text.Json.Serialization;

namespace Vessel.Api;

/// <summary>
/// Responses generated by Vessel itself (as opposed to proxied backend responses) are
/// marked with an <c>X-Vessel-Error</c> header and a JSON body whose error source is
/// "vessel", so clients and humans can always tell the two apart.
/// </summary>
public static class VesselErrors
{
    public const string Header = "X-Vessel-Error";

    public const string UnknownBackend = "unknown_backend";
    public const string UpstreamUnreachable = "upstream_unreachable";
    public const string UpstreamTimeout = "upstream_timeout";
    public const string NotFound = "not_found";

    public static Task Write(
        HttpContext context, int statusCode, string code, string message, string[]? backends = null)
    {
        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/json; charset=utf-8";
        context.Response.Headers[Header] = code;

        var payload = new ErrorPayload(new ErrorBody("vessel", code, message, backends));
        return JsonSerializer.SerializeAsync(
            context.Response.Body, payload, ApiJsonContext.Default.ErrorPayload, context.RequestAborted);
    }
}

public sealed record ErrorPayload(ErrorBody Error);

public sealed record ErrorBody(
    string Source,
    string Code,
    string Message,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string[]? Backends);

public sealed record StatusPayload(
    string Name,
    string Version,
    string Listen,
    string DefaultBackend,
    StatusBackend[] Backends);

public sealed record StatusBackend(string Name, string BaseUrl, string Type, bool Default);

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, WriteIndented = true)]
[JsonSerializable(typeof(ErrorPayload))]
[JsonSerializable(typeof(StatusPayload))]
public sealed partial class ApiJsonContext : JsonSerializerContext;
