using System.Text.Json;
using System.Text.Json.Serialization;
using Vessel.Capture;

namespace Vessel.Api;

/// <summary>
/// Responses generated by Vessel itself (as opposed to proxied backend responses) are
/// marked with an <c>X-Vessel-Error</c> header and a JSON body whose error source is
/// "vessel", so clients and humans can always tell the two apart.
/// </summary>
public static class VesselErrors
{
    public const string Header = "X-Vessel-Error";

    public const string UnknownBackend = "unknown_backend";
    public const string UpstreamUnreachable = "upstream_unreachable";
    public const string UpstreamTimeout = "upstream_timeout";
    public const string NotFound = "not_found";
    public const string InvalidRequest = "invalid_request";
    public const string InvalidConfig = "invalid_config";
    public const string FormatMismatch = "format_mismatch";
    public const string MissingReplayAuth = "missing_replay_auth";

    /// <summary>R06 — the writer gave up; commands that need it can't be honoured (503).</summary>
    public const string CaptureStopped = "capture_stopped";

    /// <summary>Capture-only code (no response is written — nobody's listening).</summary>
    public const string ClientDisconnect = "client_disconnect";

    /// <summary>D03 — the request's Host header isn't loopback or the configured listener (control plane only).</summary>
    public const string ForbiddenHost = "forbidden_host";

    /// <summary>D03 — a mutating <c>/vessel/api/*</c> request failed the same-origin check.</summary>
    public const string ForbiddenOrigin = "forbidden_origin";

    public static Task Write(
        HttpContext context, int statusCode, string code, string message, string[]? backends = null)
    {
        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/json; charset=utf-8";
        context.Response.Headers[Header] = code;

        var payload = new ErrorPayload(new ErrorBody("vessel", code, message, backends));
        return JsonSerializer.SerializeAsync(
            context.Response.Body, payload, ApiJsonContext.Default.ErrorPayload, context.RequestAborted);
    }
}

public sealed record ErrorPayload(ErrorBody Error);

public sealed record ErrorBody(
    string Source,
    string Code,
    string Message,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string[]? Backends);

public sealed record StatusPayload(
    string Name,
    string Version,
    string Listen,
    string DefaultBackend,
    StatusBackend[] Backends,
    CaptureHealth Capture,
    McpStatus Mcp,
    ListenSecurity ListenSecurity,
    // H0b(1) — this process's run id, so a client can distinguish a restart from a reconnect.
    string ServerRunId,
    SetupStatus Setup);

public sealed record StatusBackend(
    string Name,
    string BaseUrl,
    string Type,
    bool Default,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? AuthEnv,
    BackendHealth Health);

/// <summary>
/// R06 — whether the background writer is still recording. A give-up used to be visible
/// only as one log line; the UI needs it to tell the user that traffic is still being
/// proxied but nothing is being captured (the banner is a separate frontend item).
/// </summary>
public sealed record CaptureHealth(
    bool Recording,
    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)] string? StoppedReason);

/// <summary>The live state of Vessel's read-only MCP endpoint.</summary>
public sealed record McpStatus(bool Enabled);

/// <summary>The actual bound listener's exposure, used for the persistent UI notice.</summary>
public sealed record ListenSecurity(bool IsNonLoopback, bool IsContainer);

/// <summary>
/// #11 — first-run setup state. <paramref name="FirstRun"/> is true when this process
/// created the config file; <paramref name="DefaultBackendReachable"/> carries the
/// one-shot first-run probe of the default backend, and is null on every later run (no
/// probe ran) — never confuse it with the passively observed <see cref="BackendHealth"/>.
/// </summary>
public sealed record SetupStatus(bool FirstRun, bool? DefaultBackendReachable);
